### PR TITLE
Add hrefs starting with 'mailto:' and 'tel:' to the list of hrefs that should not be loaded by the reverse proxy.

### PR DESCRIPTION
**Pull request by phseiff**
See [this comment](https://github.com/Gusted/darkreader-web/issues/8#issuecomment-787216256)

### CODE REVIEW

**Comment by phseiff** [comment]
I just checked with the deployed pull request, and tel- as well as mailto-hrefs appear to work correctly now (you can check it too with the exemplary websites provided by my comment on issue #8 ).

**Comment by Gusted** [comment]
I will merge this for now, however this could be an problem to a greater problem, because the HTML Living standard also allows custom schemes to be [registered](https://html.spec.whatwg.org/#custom-handlers) and also includes an pre-defined list we also technically should check for.

**Comment by phseiff** [comment]
> this could be an problem to a greater problem, because the HTML Living standard also allows custom schemes to be registered

Maybe it would work better with a whitelist rather than a blacklist of schemes, so instead of loading every URL as long as it **doesn't** start with one of a specified set of protocols and schemes, it's only loaded if it starts with a scheme from a hard coded set of protocols supported by modern browsers? Because I assume that registering schemes does not extend to registering protocols to interact with a server backend, or at least, it's probably less often used to do so than it is for frontend things.
> and also includes an pre-defined list we also technically should check for.

Screenshot from the specification website (dropping it here for myself for easier accessibility):
> image

**Comment by Gusted** [comment]
> Screenshot from the specification website (dropping it here for myself for easier accessibility):

Not the only one
https://html.spec.whatwg.org/#safelisted-scheme

image


> Maybe it would work better with a whitelist rather than a blacklist of schemes, so instead of loading every URL as long as it **doesn't** start with one of a specified set of protocols and schemes, it's only loaded if it starts with a scheme from a hard coded set of protocols supported by modern browsers?

That could work, I know for every `valid` url the `.href` property is formatted to either `http://` or `https://`. So we could use that to check for it and than use the `getAttribute` again to get the correct absolute URL to use for loading.

> Because I assume that registering schemes does not extend to registering protocols to interact with a server backend, or at least, it's probably less often used to do so than it is for frontend things.

image
As seen in the great example from the w3 spec. Lets take it step for step and see where the problem relies.
1. It registers these new protocol called `web+soup` and in this examples, oh when you(the browser) uses this protocol. You get the origin URL(or Origin + path? Unsure) and then as `path` you uses `soup?url=%s` format as defined in the function, `%s` is the variable here which is explained later.
2. The website defines this element `a` also know as Anchor element with an href `web+soup:chicken-kïwi` which is an now valid href.
3. Oh hey the user clicks on this element and now we need to serve a new url. We see in these href it uses `web+soup` and see it's has an `handler` that says `soup?url=%s` So now we get the origin URL(or Origin + path? Unsure) which is https://www.example.com + soup?url=%s. Now the %s is replaced by chicken-kïwi as it's defined in this href. And later URI Encoded to serve as an useable URL.

A good solution to this is to intercept `registerProtocolHandler`, which purely exist for 1 purpose, to set an Map with the protocol + format string. So when we see `href=web+soup` we know what to do with it and "recreate" intended behaviour onto the right proxy URL.

Sound complicated? The actual code to fix this problem is much much easier to understand.

Regards,
Gusted

**Comment by Gusted** [comment]
> Sound complicated? The actual code to fix this problem is much much easier to understand.

I've documented almost every step. So it should be understandable. How this fix works.
https://github.com/Gusted/darkreader-web/commit/643b05a17ed81f6a9a3d868d74ca65d2f9a4f5a3#diff-78bb005ca752086400a648d8aa3e60ce6f666e213da508caabd464d3bfeaf6a2R34

**Comment by phseiff** [comment]
Thank you for the quick & quality explanation of how registering protocols work, and for linking your code - I read it and it is indeed quite understandable, the documentation certainly works wonders. Feels like I learned something new again :)

Regards,
phseiff

**Comment by Gusted** [comment]
> Thank you for the quick & quality explanation of how registering protocols work, and for linking your code - I read it and it is indeed quite understandable, the documentation certainly works wonders.

I've always wanted to write code that has every line of code an explanation what it does, however never _really_ felt the need to it. Until now as it uses some good hackery without any comments, I hope I can do it for every line of code in darkreader-web in the future, as especially for proxy.ts it will have more hackery to make certain things works.

> Feels like I learned something new again :)

It's the edge of Javascript abilities what it can do :). 

Regards,
Gusted

**Pull request merged**
